export const sample_books = [
  {
    id: '1',
    name: 'Harry Potter',
    readTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'book-1.jpg',
    tags: ['Scifi', 'Novel', ],
  },
  {
    id: '2',
    name: 'Sherlock Holmes',
    price: 20,
    readTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'book-2.jpg',
    tags: ['Shortstory'],
  },
  {
    id: '3',
    name: 'Little House',
    price: 5,
    readTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'book-3.jpg',
    tags: ['Novel'],
  },
  {
    id: '4',
    name: 'Tom Sawywr',
    price: 2,
    readTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'book-4.jpg',
    tags: ['Scifi'],
  },
  {
    id: '5',
    name: 'Mother',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'book-5.jpg',
    tags: ['Music'],
  },
  {
    id: '6',
    name: 'Secret Seven',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'book-6.jpg',
    tags: ['Kids'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'Scifi', count: 4 },
  { name: 'Novel', count: 2 },
  { name: 'Kids', count: 3 },
  { name: 'Adults', count: 2 },
  { name: 'Shortstory', count: 1 },
  { name: 'Music', count: 1 },
  { name: 'Drama', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
